NO-ISSUE: build_bootc_image.py-Add dry_run arg for rpm build
It will fix following error
```
12:36:33.617973327 An error occurred: run_command() missing 1 required positional argument: 'dry_run'
Traceback (most recent call last):
  File "/home/prkumar/work/github/microshift/test/bin/pyutils/build_bootc_images.py", line 548, in main
    common.run_command(f"{SCRIPTDIR}/build_rpms.sh")
TypeError: run_command() missing 1 required positional argument: 'dry_run'
12:36:33.619852304 Running atexit cleanup
```